### PR TITLE
Unit test for model's fields

### PR DESCRIPTION
**Pull request by quandang246**
## Related Tickets
- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/69770)

## WHAT (optional)
- Unit test for a model's fields.

## HOW
- Adding myapp_test

### CODE REVIEW

**Review by riderhuy — APPROVED** [review]
approve

**Review by tdanhjv — APPROVED** [review]
approve

**Comment by quandang246** [comment]
ready

**Review by huongnt-2545 — COMMENTED** [review]
Cấu trúc sai folder test

**Pull request closed without merging**
