### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by quandang246**
## Related Tickets
- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/69770?issue_count=11&issue_position=1&next_issue_id=69715)

## WHAT (optional)
- Unit test

## HOW
- Create unit test for models, views and forms

### CODE REVIEW

**Review by riderhuy — APPROVED** [review]
Approve

**Review by tdanhjv — APPROVED** [review]

**Comment by quandang246** [comment]
ready

**Review by huongnt-2545 — APPROVED** [review]
EM ignore folder chứa ảnh upload từ client nhé
sau đó chạy lệnh để xóa git cache folder nha

```
git rm -rf --cached /media/profile_images/
```

**Comment by huongnt-2545** [comment]
commented

**Comment by quandang246** [comment]
ready

**Pull request merged**
