### PR TITLE
Fix model + hien thi homepage + add thu vien Leaflet

### PR DESCRIPTION
**Pull request by tdanhjv**
## Related Tickets
- [ticket 67629](https://edu-redmine.sun-asterisk.vn/issues/67629)

## WHAT (optional)
- Fix model + hien thi homepage + add thu vien Leaflet

## HOW
- Chỉnh sửa file models.py, view.py và các file html liên quan đến homepage

## Evidence (Screenshot or Video)
image

### CODE REVIEW

**Review by quandang246 — APPROVED** [review]
ok

**Review by riderhuy — APPROVED** [review]
approve

**Comment by quandang246** [comment]
ok

**Comment by tdanhjv** [comment]
ready

**Review by huongnt-2545 — APPROVED** [review]
merged

**Pull request merged**
